### PR TITLE
don't fail prs on no assignee if renovate

### LINKED ISSUE #110: Disable assignee check for renovate PRs
There's a race condition where peril checks for assignees before renovate has a chance to add them. It'd be nice to just disable that check for renovate PRs.

### PR DESCRIPTION
**Pull request by zephraph**
We're pretty consistently getting peril failures in reaction on renovate PRs where peril claims there's no assignee. Renovate adds an assignee after the PR is created and therefore tends to trip our PR rule (rfc13). 

Here's an example: https://github.com/artsy/reaction/pull/2350

Fixes #110.

### CODE REVIEW

File: org/allPRs.ts [hunk 1]
```diff
@@ -49,8 +49,9 @@ export const rfc7 = async () => {
 // https://github.com/artsy/peril-settings/issues/13
 export const rfc13 = async () => {
   const pr = danger.github.pr
+  const isRenovate = pr.user.login.toLowerCase().includes("renovate")
   const wipPR = pr.title.includes("WIP ") || pr.title.includes("[WIP]")
-  if (!wipPR && pr.assignee === null) {
+  if (!isRenovate && !wipPR && pr.assignee === null) {
```
Comment (orta) [inline org/allPRs.ts]: this could check if the user is a bot instead, then it can do it for any automated PRs?
